spring.application.name=Cours_Service


spring.datasource.url=jdbc:mysql://localhost:3306/Cours_Service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=


server.servlet.context-path=/Cours_Service
server.port=5059
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}